<ul>
<li>This is sample/index/index.phtml
	<ul>
		<li>
			<?php 
			echo $this->getPlugin('my-plugin/index/render-view'); 
			?>
		</li>
		<li>
			<?php 
			echo $this->getPlugin('my-plugin/index/render-closure', 'ViewModel'); 
			?>
		</li>
		<li>
			<?php 
			$plugin = $this->getPlugin('my-plugin/index/render-closure', 'Array');
			var_dump($plugin);
			?>
		</li>
		<li>
			<?php 
			$plugin = $this->getPlugin('my-plugin/index/render-closure', 'String');
			var_dump($plugin);
			?>
		</li>
	</ul>
</li>
</ul>